"""Fail-closed authority verification for V2 execution evidence."""

from .verifier import (
    AuthorityClaim,
    AuthorityAttestationResult,
    AuthorityAttestationStatus,
    AuthorityDecision,
    AuthorityAttestationConflictError,
    AuthorityNonceReplayError,
    AuthorityReceiptLoader,
    AuthorityReceiptReference,
    AuthorityTrustKey,
    AuthorityVerificationLevel,
    AuthorityVerificationError,
    DenyAllAuthorityVerifier,
    Ed25519AuthorityVerifier,
    EvidenceAuthorityVerifier,
    MySQLAuthorityReceiptLoader,
    MySQLRegistryBackedAuthorityVerifier,
    MySQLReceiptRegistryAuthorityVerifier,
    SignedAuthorityReceipt,
    append_authority_attestation,
    authority_receipt_signature_message,
    build_authority_claim,
    build_instrument_rule_authority_claim,
    load_authority_attestation,
    require_verified_authority,
    require_verified_instrument_rule_authority,
)

__all__ = [
    "AuthorityClaim",
    "AuthorityAttestationResult",
    "AuthorityAttestationStatus",
    "AuthorityDecision",
    "AuthorityAttestationConflictError",
    "AuthorityNonceReplayError",
    "AuthorityReceiptLoader",
    "AuthorityReceiptReference",
    "AuthorityTrustKey",
    "AuthorityVerificationLevel",
    "AuthorityVerificationError",
    "DenyAllAuthorityVerifier",
    "Ed25519AuthorityVerifier",
    "EvidenceAuthorityVerifier",
    "MySQLAuthorityReceiptLoader",
    "MySQLRegistryBackedAuthorityVerifier",
    "MySQLReceiptRegistryAuthorityVerifier",
    "SignedAuthorityReceipt",
    "append_authority_attestation",
    "authority_receipt_signature_message",
    "build_authority_claim",
    "build_instrument_rule_authority_claim",
    "load_authority_attestation",
    "require_verified_authority",
    "require_verified_instrument_rule_authority",
]
