"""The storage encoding must not change any frozen business fact or hash."""
import base64
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import zlib

import pytest

from server.common import analysis_pool_receipt as receipts


@pytest.fixture
def historical():
    # Produced by the original, deployed 95f343f implementation using only
    # synthetic rows; never regenerated by the codec under test.
    return json.loads((Path(__file__).parent / "fixtures/analysis_snapshots_v1.json").read_text(encoding="utf-8"))


def rebuild(kind, payload):
    if kind == "preliminary":
        return receipts.build_preliminary_analysis_snapshot(**{
            key: payload[key] for key in (
                "analysis_rows", "candidate_rows", "scored_rows",
                "market_mood_score", "flow_date", "hot_date",
            )
        })
    return receipts.build_score_snapshot(**{
        key: payload[key] for key in (
            "trade_date", "decision_at", "run_uid", "build_sha",
            "analysis_rows", "scored_rows",
        )
    })


def decoder(kind):
    return receipts.decode_preliminary_analysis_snapshot if kind == "preliminary" else receipts.decode_score_snapshot


@pytest.mark.parametrize("kind", ["preliminary", "score"])
def test_new_storage_preserves_deployed_logical_payload_and_every_row_hash(historical, kind):
    original = historical[kind]
    original_copy = deepcopy(original)
    frozen = decoder(kind)(original)
    current = rebuild(kind, frozen)
    assert current["encoding"] == "zlib-base64-dictionary-columnar-json-v1"
    assert current["payload_sha256"] == original["payload_sha256"]
    restored = decoder(kind)(current)
    assert restored == frozen
    assert receipts.canonical_sha256(restored) == original["payload_sha256"]
    for key in ("analysis_rows", "scored_rows"):
        assert [receipts.canonical_sha256(row) for row in restored[key]] == [receipts.canonical_sha256(row) for row in frozen[key]]
    assert len(restored["scored_rows"]) == 81
    assert "optional_null" not in restored["scored_rows"][0]
    assert restored["scored_rows"][1]["optional_null"] is None
    assert original == original_copy


@pytest.mark.parametrize("kind", ["preliminary", "score"])
@pytest.mark.parametrize("historical_encoding", [False, True])
def test_both_storage_encodings_reject_tampered_roots(historical, kind, historical_encoding):
    envelope = historical[kind] if historical_encoding else rebuild(kind, decoder(kind)(historical[kind]))
    envelope["payload_sha256"] = "0" * 64
    with pytest.raises(ValueError):
        decoder(kind)(envelope)


@pytest.mark.parametrize("kind", ["preliminary", "score"])
def test_new_snapshot_rejects_hidden_zlib_trailer_even_if_hash_is_resealed(historical, kind):
    envelope = rebuild(kind, decoder(kind)(historical[kind]))
    compressed = base64.b64decode(envelope["payload_base64"]) + zlib.compress(b"hidden")
    envelope["payload_base64"] = base64.b64encode(compressed).decode("ascii")
    envelope["compressed_sha256"] = hashlib.sha256(compressed).hexdigest()
    with pytest.raises(ValueError):
        decoder(kind)(envelope)


@pytest.mark.parametrize("kind", ["preliminary", "score"])
def test_wire_decompression_budget_is_enforced(historical, monkeypatch, kind):
    envelope = rebuild(kind, decoder(kind)(historical[kind]))
    monkeypatch.setattr(receipts, "_SNAPSHOT_WIRE_MAX_BYTES", 64)
    with pytest.raises(ValueError):
        decoder(kind)(envelope)


def test_historical_encodings_preserve_their_original_distinct_size_domains(historical, monkeypatch):
    # Old preliminary had no decompression ceiling; old score did. A reduced
    # bound proves the distinction without a 128 MiB regression-test allocation.
    monkeypatch.setattr(receipts, "_SNAPSHOT_WIRE_MAX_BYTES", 64)
    assert len(receipts.decode_preliminary_analysis_snapshot(historical["preliminary"])["scored_rows"]) == 81
    with pytest.raises(ValueError):
        receipts.decode_score_snapshot(historical["score"])


@pytest.mark.parametrize("kind", ["preliminary", "score"])
def test_storage_capacity_failure_reports_sizes(historical, monkeypatch, kind):
    payload = decoder(kind)(historical[kind])
    monkeypatch.setattr(receipts, "PRELIMINARY_ANALYSIS_SNAPSHOT_MAX_BYTES", 1)
    with pytest.raises(ValueError, match=r"encoded_bytes=\d+, raw_bytes=\d+, limit_bytes=1"):
        rebuild(kind, payload)
