// Original, dependency-free pixel drawings. Each character is one logical pixel.
// The dot is transparent. Characters use the warm, three-colour console palette.
const MARIO = { R: '#e33b16', B: '#713d12', S: '#ffba79', Y: '#ffd47c' };
const ENEMY = { B: '#a94d1b', D: '#58250b', T: '#ffba79', W: '#fff4d6', K: '#231608' };

function sprite(palette, pixels, width = 16, height = 16) {
  if (pixels.length !== height) throw new Error(`Expected ${height} rows, got ${pixels.length}`);
  const rows = pixels.map((row, index) => {
    if (row.length > width) throw new Error(`Row ${index} exceeds ${width}: ${row}`);
    for (const pixel of row) {
      if (pixel !== '.' && !Object.hasOwn(palette, pixel)) throw new Error(`Unknown colour: ${pixel}`);
    }
    return row.padEnd(width, '.');
  });
  return { palette: { ...palette }, pixels: rows };
}

const smallHead = [
  '.....RRRRR......',
  '....RRRRRRRRR...',
  '....BBBSSBS.....',
  '...BSBSSSBSSS...',
  '...BSBBSSSBSSS..',
  '...BBSSSSBBBB...',
  '.....SSSSSSS....',
];

const bigHead = [
  '.....RRRRRR.....',
  '....RRRRRRRR....',
  '...RRRRRRRRRR...',
  '...RRRRRRRRRRR..',
  '...BBBSSSBSS....',
  '..BSSBSSSBSSS...',
  '..BSSBBSSSBSSS..',
  '..BBBSSSSBBBBB..',
  '...BSSSSSSSSS...',
  '....SSSSSSSS....',
];

const smallIdle = sprite(MARIO, [...smallHead,
  '....BBRBB.......',
  '...BBBRBBRBBB...',
  '..BBBBRRRRBBBB..',
  '..SSBRYRYRBSS...',
  '..SSSRRRRRRSSS..',
  '..SSRRRRRRRRSS..',
  '....RRR..RRR....',
  '...BBB....BBB...',
  '..BBBB....BBBB..',
]);

const smallRun1 = sprite(MARIO, [...smallHead,
  '.....BRBB.......',
  '...BBBRRRSS.....',
  '..BBBBRRRSSS....',
  '..SSBBRRYRR.....',
  '..SSSRRRRRRR....',
  '...SSRRRRRBBB...',
  '.....RRR..BBBB..',
  '....BBB.........',
  '...BBBB.........',
]);

const smallRun2 = sprite(MARIO, [...smallHead,
  '....BBRBB.......',
  '..SSBBRBBRBBB...',
  '.SSSBBRRRRBBBB..',
  '..SSBRYRYRBSSS..',
  '....RRRRRRRSSS..',
  '..BBRRRRRRRRSS..',
  '.BBBRRR..RRR....',
  '.BBB......BBB...',
  '..........BBBB..',
]);

const smallJump = sprite(MARIO, [
  '.....RRRRR..SSS.',
  '....RRRRRRRRSSS.',
  '....BBBSSBS.BBS.',
  '...BSBSSSBSSBBB.',
  '...BSBBSSSBSSBB.',
  '...BBSSSSBBBBBB.',
  '.....SSSSSSSBB..',
  '..SSSBBRBBRBB...',
  '.SSSSBBRBBRB....',
  '..SSBBRRRRRR..B.',
  '....BRRYRYRR.BBB',
  '....RRRRRRRRRBBB',
  '...RRRRRRRRRRBBB',
  '..BBBRRR..RRR...',
  '.BBBB...........',
  '.BBB............',
]);

const bigIdle = sprite(MARIO, [...bigHead,
  '....BBRBB.......',
  '...BBBRBBRB.....',
  '..BBBBRBBRBBB...',
  '..BBBBRBBRBBBB..',
  '.BBBBBRRRRBBBB..',
  '.BBBBBRYRYBBBB..',
  '.SSSBBRRRRBSSS..',
  '.SSSSBRRRRBSSSS.',
  '.SSSSBRRRRBSSSS.',
  '.SSS.RRRRRR.SSS.',
  '.....RRRRRR.....',
  '....RRRRRRRR....',
  '...RRRRRRRRRR...',
  '...RRRRRRRRRR...',
  '...RRRR..RRRR...',
  '...RRRR..RRRR...',
  '...RRRR..RRRR...',
  '...RRRR..RRRR...',
  '...BBBB..BBBB...',
  '..BBBBB..BBBBB..',
  '.BBBBBB..BBBBBB.',
  '.BBBBBB..BBBBBB.',
], 16, 32);

const bigRun1 = sprite(MARIO, [...bigHead,
  '.....BRBB.......',
  '....BBRBBR......',
  '...BBBRBBRSS....',
  '..BBBBRBBRSSS...',
  '..BBBBRRRRSSSS..',
  '..BBBBRYRRSSSS..',
  '.SSSBBRRRRBSS...',
  '.SSSSBRRRRBB....',
  '.SSSSBRRRRR.....',
  '..SS.RRRRRRR....',
  '.....RRRRRRR....',
  '....RRRRRRRRR...',
  '....RRRRRRRRR...',
  '....RRRRRRRRRR..',
  '....RRRR.RRRRR..',
  '....RRRR..RRRR..',
  '...RRRR...BBBB..',
  '...RRRR..BBBBBB.',
  '..BBBB...BBBBBB.',
  '..BBBB....BBBB..',
  '.BBBBB..........',
  '.BBBBB..........',
], 16, 32);

const bigRun2 = sprite(MARIO, [...bigHead,
  '....BBRBB.......',
  '...BBBRBBRB.....',
  '..SSBBRBBRBBB...',
  '.SSSSBRBBRBBBB..',
  '.SSSSBRRRRBBBBB.',
  '..SSSBRYRYBBBBB.',
  '...BBBRRRRBSSSS.',
  '....BBRRRRBSSSS.',
  '.....RRRRRRSSSS.',
  '....RRRRRRR.SS..',
  '...RRRRRRRRR....',
  '..RRRRRRRRRR....',
  '.RRRRRRRRRRRR...',
  '.RRRRR..RRRRR...',
  '.RRRR....RRRR...',
  '.BBBB....RRRR...',
  'BBBBB....RRRR...',
  'BBBBB.....RRR...',
  '.BBBB.....BBBB..',
  '..........BBBBB.',
  '..........BBBBB.',
  '...........BBBB.',
], 16, 32);

const bigJump = sprite(MARIO, [
  '.....RRRRRR.SSS.',
  '....RRRRRRRRSSSS',
  '...RRRRRRRRRSSSS',
  '...RRRRRRRRRRSSS',
  '...BBBSSSBSS.BBB',
  '..BSSBSSSBSSSBBB',
  '..BSSBBSSSBSSBBB',
  '..BBBSSSSBBBBBBB',
  '...BSSSSSSSSSBBB',
  '....SSSSSSSS.BBB',
  '....BBRBB...BBB.',
  '...BBBRBBRBBBBB.',
  '..BBBBRBBRBBBB..',
  '.BBBBBRBBRBBBB..',
  '.BBBBBRRRRBBB...',
  'SSSBBBRYRYBBB...',
  'SSSSBBRRRRBB....',
  'SSSSBBRRRRR.....',
  'SSS.BRRRRRRR....',
  '....RRRRRRRR..B.',
  '...RRRRRRRRR.BBB',
  '..RRRRRRRRRRRBBB',
  '.RRRRRRRRRRRRBBB',
  '.RRRRRR..RRRRBBB',
  '.RRRRRR...RRRBB.',
  '.RRRRR..........',
  '.RRRR...........',
  '.BBBB...........',
  'BBBBB...........',
  'BBBBB...........',
  '.BBBB...........',
  '..BBB...........',
], 16, 32);

const goombaHead = [
  '.....BBBBBB.....',
  '....BBBBBBBB....',
  '...BBBBBBBBBB...',
  '..BBBBBBBBBBBB..',
  '.BBBDBBBBBBDBBB.',
  '.BBBWDDBBDDWBBB.',
  'BBBBWKWBBWKWBBBB',
  'BBBBWWWBBWWWBBBB',
  'BBBBBBBBBBBBBBBB',
  '.BBBBBBBBBBBBBB.',
  '..BBBBBBBBBBBB..',
  '....TTTTTTTT....',
];

const goomba1 = sprite(ENEMY, [...goombaHead,
  '...DDTTTTTTDD...',
  '..DDDDTTTTDDDD..',
  '.DDDDD....DDDD..',
  '.DDDD......DDD..',
]);
const goomba2 = sprite(ENEMY, [...goombaHead,
  '...DDTTTTTTDD...',
  '..DDDDTTTTDDDD..',
  '..DDDD....DDDDD.',
  '..DDD......DDDD.',
]);
const goombaFlat = sprite(ENEMY, [
  '................', '................', '................', '................',
  '................', '................', '................', '................',
  '................', '................', '................',
  '...BBBBBBBBBB...', '.BBBBWBBWBWBBBB.', 'BBBBBBBBBBBBBBBB',
  '..DDDTTTTTTDDD..', '.DDDDD....DDDDD.',
]);

const mushroom = sprite({ R: '#e33b16', W: '#fff4d6', S: '#ffba79', D: '#713d12' }, [
  '.....RRRRRR.....',
  '...RRRRRRRRRR...',
  '..RRWWRRRRWWRR..',
  '.RRWWWWRRWWWWRR.',
  '.RWWWWWRRWWWWWR.',
  'RRWWWWRRRRWWWWRR',
  'RRRWWRRRRRRWWRRR',
  'RRRRRRWWWWRRRRRR',
  'RRRRRWWWWWWRRRRR',
  '.RRRRWWWWWWRRRR.',
  '..DDDDDDDDDDDD..',
  '...SSSSSSSSSS...',
  '...SSDSSSSDSS...',
  '...SSDSSSSDSS...',
  '....SSSSSSSS....',
  '.....DDDDDD.....',
]);

const coin = sprite({ D: '#a65b08', G: '#ffb51b', Y: '#ffe457', H: '#fff5ac' }, [
  '......DDDD......',
  '.....DYYYYD.....',
  '....DYHYYGGD....',
  '....DYHDDGGD....',
  '...DYHGDGGGGD...',
  '...DYHGDGGGGD...',
  '...DYHGDGGGGD...',
  '...DYHGDGGGGD...',
  '...DYHGDGGGGD...',
  '...DYHGDGGGGD...',
  '...DYHGDGGGGD...',
  '...DYHGDGGGGD...',
  '....DYHDDGGD....',
  '....DYHYYGGD....',
  '.....DYYYYD.....',
  '......DDDD......',
]);

const question = sprite({ D: '#8b3c12', A: '#ed9229', L: '#ffd27c', Q: '#72310b' }, [
  'DDDDDDDDDDDDDDDD',
  'DLLLLLLLLLLLLLAD',
  'DLAAAAAAAAAAAAAD',
  'DLADAAAAAAAADAAD',
  'DLAAAQQQQAAAAAAD',
  'DLAAQQAAQQAAAAAD',
  'DLAAQQAAQQAAAAAD',
  'DLAAAAAQQAAAAAAD',
  'DLAAAAQQAAAAAAAD',
  'DLAAAAQQAAAAAAAD',
  'DLAAAAAAAAAAAAAD',
  'DLAAAAQQAAAAAAAD',
  'DLAAAAQQAAAAAAAD',
  'DLADAAAAAAAADAAD',
  'DAAAAAAAAAAAAAAD',
  'DDDDDDDDDDDDDDDD',
]);

const brick = sprite({ D: '#562a16', B: '#bd5229', L: '#f48a51', S: '#813719' }, [
  'LLLLLLLDLLLLLLLD',
  'LBBBBBBDLBBBBBBD',
  'LBBBBBBDLBBBBBBD',
  'LBBBBBBDLBBBBBBD',
  'LBBBBBBDLBBBBBBD',
  'LBBBBBBDLBBBBBBD',
  'SSSSSSSDSSSSSSSD',
  'DDDDDDDDDDDDDDDD',
  'LLLDLLLLLLLDLLLL',
  'BBBDLBBBBBBDLBBB',
  'BBBDLBBBBBBDLBBB',
  'BBBDLBBBBBBDLBBB',
  'BBBDLBBBBBBDLBBB',
  'BBBDLBBBBBBDLBBB',
  'SSSDSSSSSSSDSSSS',
  'DDDDDDDDDDDDDDDD',
]);

const ground = sprite({ D: '#633018', B: '#c66a35', L: '#ffb97d', S: '#98491e' }, [
  'LLLLLLLLLLLLLLLL',
  'LBBBBBBBBBBBBBBD',
  'LBLLLLLLLLLLLLBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLBBBBBBBBBBSBD',
  'LBLSSSSSSSSSSSBD',
  'LBBBBBBBBBBBBBBD',
  'LDDDDDDDDDDDDDLD',
  'DDDDDDDDDDDDDDDD',
]);

const used = sprite({ D: '#6c3010', B: '#bd6e30', L: '#d99650', S: '#925020' }, [
  'DDDDDDDDDDDDDDDD',
  'DLLLLLLLLLLLLLBD',
  'DLBBBBBBBBBBBBDD',
  'DLBDBBBBBBBDBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBBBBBBBBBBBBDD',
  'DLBDBBBBBBBDBBDD',
  'DBSSSSSSSSSSSSDD',
  'DBDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDD',
]);

const bush = sprite({ D: '#1a6224', G: '#38ad35', L: '#81da43' }, [
  '................................',
  '................................',
  '.............DDDDDD.............',
  '...........DDLLLLLLDD...........',
  '..........DLLLLLLLLLLD..........',
  '.....DDDDDLLLLLLLLLLLLDDDD......',
  '...DDLLLLDLLLLLLLLLLLDLLLLDD....',
  '..DLLLLLLLLLLLLLLLLLLLLLLLLD....',
  '.DLLLLLLLLLLLLLLLLLLLLLLLLLLD...',
  '.DLLLLLLLLLLLLLLLLLLLLLLLLLLD...',
  'DLLLLLLLLLLLLLLLLLLLLLLLLLLLLD..',
  'DLLLLLLLLLLLLLLLLLLLLLLLLLLLLD..',
  'DGLLLLLLLLGGLLLLLLGGLLLLLLLGGD..',
  '.DGGLLLLGGGGGLLLLGGGGLLLLLGGD...',
  '..DGGGGGGGGGGGGGGGGGGGGGGGGD....',
  '...DDDDDDDDDDDDDDDDDDDDDDDD.....',
], 32, 16);

const hill = sprite({ D: '#206a25', G: '#66be3b', L: '#88d845' }, [
  '..............DDDD..............',
  '............DDLLLLDD............',
  '...........DLLLLLLLLD...........',
  '..........DLLLLLLLLLLD..........',
  '.........DLLLLLLLLLLLLD.........',
  '........DLLLLLLLLLLLLLLD........',
  '.......DLLLLLLLLLLLLLLLLD.......',
  '......DLLLLLGLLLLLLLLLLLLD......',
  '.....DLLLLLGGGLLLLLGLLLLLLD.....',
  '....DLLLLLGGGGGLLLGGGLLLLLLD....',
  '...DLLLLLLLGGGLLLGGGGGLLLLLLD...',
  '..DLLLLLLLLLGLLLLLGGGLLLLLLLLD..',
  '.DLLLLLLLLLLLLLLLLLGLLLLLLLLLLD.',
  'DLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLD',
  'DLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLD',
  'DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD',
], 32, 16);

const cloud = sprite({ D: '#516faa', W: '#fffdf4', S: '#c3e5ef' }, [
  '.............DDDDDD.............',
  '...........DDWWWWWWDD...........',
  '..........DWWWWWWWWWWD..........',
  '..........DWWWWWWWWWWD..........',
  '......DDDDWWWWWWWWWWWWDDDD......',
  '.....DWWWWWWWWWWWWWWWWWWWWD.....',
  '....DWWWWWWWWWWWWWWWWWWWWWWD....',
  '..DDWWWWWWWWWWWWWWWWWWWWWWWWDD..',
  '.DWWWWWWWWWWWWWWWWWWWWWWWWWWWWD.',
  'DWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWD',
  'DWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWD',
  'DWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWD',
  'DSSWWWWWWWWWWWWWWWWWWWWWWWWWWSSD',
  '.DSSSSSWWWWWWWWWWWWWWWWSSSSSSSD.',
  '..DDSSSSSSSSSSSSSSSSSSSSSSSSDD..',
  '....DDDDDDDDDDDDDDDDDDDDDDDD....',
], 32, 16);

export const sprites = {
  smallIdle, smallRun1, smallRun2, smallJump,
  bigIdle, bigRun1, bigRun2, bigJump,
  goomba1, goomba2, goombaFlat, mushroom, coin,
  question, brick, ground, used, bush, hill, cloud,
};

export default sprites;
